import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";




const font = Poppins({
  subsets: ["latin"],
  weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
         
        <Navbar />
        
        {children}
        
      </body>
    </html>
  );
}
